# Generated by Django 4.2.7 on 2024-04-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="description_preview",
            field=models.CharField(default="", max_length=300),
        ),
    ]
